// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbL6vrjbXRO8HHeOXwJmwyZjZtp9tG0jk',
    appId: '1:267661849190:web:f0c249d9cad165eb2fb3a7',
    messagingSenderId: '267661849190',
    projectId: 'task-52aba',
    authDomain: 'task-52aba.firebaseapp.com',
    storageBucket: 'task-52aba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhDKukj8XVlsv52mMatBJPnQocnc4n3Y',
    appId: '1:267661849190:android:786b6457c3f8dde52fb3a7',
    messagingSenderId: '267661849190',
    projectId: 'task-52aba',
    storageBucket: 'task-52aba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARGpwHTSrcymQ8M1OJb01412tvIqDLYzU',
    appId: '1:267661849190:ios:0926b2e31de61f002fb3a7',
    messagingSenderId: '267661849190',
    projectId: 'task-52aba',
    storageBucket: 'task-52aba.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARGpwHTSrcymQ8M1OJb01412tvIqDLYzU',
    appId: '1:267661849190:ios:0926b2e31de61f002fb3a7',
    messagingSenderId: '267661849190',
    projectId: 'task-52aba',
    storageBucket: 'task-52aba.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbL6vrjbXRO8HHeOXwJmwyZjZtp9tG0jk',
    appId: '1:267661849190:web:41e39494bf1191982fb3a7',
    messagingSenderId: '267661849190',
    projectId: 'task-52aba',
    authDomain: 'task-52aba.firebaseapp.com',
    storageBucket: 'task-52aba.firebasestorage.app',
  );
}
